name: ml
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.12
  - pytorch
  - jupyterlab
  - scikit-learn
  - matplotlib
  - pandas
  - ipywidgets
  - pip
  - pip:
      - peft
      - transformers
      - bitsandbytes
      - evaluate
